name: Bug Report
title: '"[Bug]: <short description>"'
description: Report an issue with Econet300 home assistant integration.
labels: ["bug", "triage"]
assignees: ["jontofront"]
body:
  - type: markdown
    attributes:
      value: |
        **Please describe the bug you found. The more details you provide, the faster we can help!**

        ⚠️ **Important:** Attaching a diagnostics file helps us solve your issue much faster!

  - type: textarea
    id: problem_description
    attributes:
      label: What's the problem? 🐛
      description: Describe what's not working as expected
      placeholder: "Example: The temperature sensor shows wrong values after restart"

  - type: dropdown
    id: connected_devices
    attributes:
      label: Which ecoNET device do you have? 🔌
      description: Select your device (you can select multiple)
      multiple: true
      options:
        - ecoMAX360
        - ecoMAX810P-L
        - ecoMAX850R2-X
        - ecoMAX860P2-N
        - ecoMAX860P3-V
        - ecoSOL 300
        - ecoSOL 500
        - SControl MK1
        - Other (please specify)

  - type: input
    id: device_model_other
    attributes:
      label: Other Device Model
      description: If you selected "Other", what's your device model?
      placeholder: "e.g., ecoMAX900P"

  - type: dropdown
    id: severity
    attributes:
      label: How bad is it? 🚨
      description: Choose the severity level
      options:
        - "Critical - Nothing works"
        - "High - Major problem"
        - "Medium - Annoying but usable"
        - "Low - Minor issue"

  - type: markdown
    attributes:
      value: |
        ### Diagnostics (recommended)
        Please attach **ecoNET300 diagnostics** from Home Assistant (these are automatically redacted):

        **Settings → Devices & Services → ecoNET300 → ⋮ → Download diagnostics**

        Docs: https://www.home-assistant.io/integrations/diagnostics/

        (You can drag & drop the downloaded file into this issue.)

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots 📸
      description: Add screenshots showing the problem (drag & drop images here)
      placeholder: "Upload screenshots of error messages, wrong values, or broken UI"

  - type: markdown
    attributes:
      value: |
        ---
        ## 📊 Diagnostics File (Highly Recommended)

        **Attaching a diagnostics file helps us solve your issue MUCH faster!**

        **How to download diagnostics:**
        1. Go to **Settings → Devices & Services**
        2. Find **ecoNET300** integration
        3. Click the **⋮** menu (three dots)
        4. Click **Download diagnostics**
        5. Attach the downloaded JSON file below

        ![Download Diagnostics](https://raw.githubusercontent.com/jontofront/ecoNET-300-Home-Assistant-Integration/master/images/download_diagnostics.png)

  - type: textarea
    id: diagnostics_file
    attributes:
      label: Diagnostics File 📊
      description: "Drag & drop your diagnostics JSON file here. This file contains your device configuration and helps us debug faster. (Sensitive data like passwords is automatically redacted)"
      placeholder: "Drag & drop your diagnostics .json file here, or paste its contents"
    validations:
      required: false

  - type: input
    id: versions
    attributes:
      label: Versions 📦
      description: What versions are you using?
      placeholder: "HA: 2025.2.2, Integration: v1.1.6"

  - type: textarea
    id: additional_info
    attributes:
      label: Anything else? 💡
      description: Additional details, logs, or context that might help
      placeholder: "Optional: logs, error messages, or other relevant info"
