name: 💡 Feature Request
description: Suggest a new feature or improvement for the ecoNET-300 integration
title: "[FEATURE] "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 💡 Feature Request

        Use this template for any feature or improvement request (including new sensors/entities).

  - type: dropdown
    id: device_model
    attributes:
      label: Device Model
      description: What ecoNET device model do you have?
      options:
        - "ecoMAX360"
        - "ecoMAX810P-L"
        - "ecoMAX850R2-X"
        - "ecoMAX860P2-N"
        - "ecoMAX860P3-V"
        - "ecoSOL 300"
        - "ecoSOL 500"
        - "SControl MK1"
        - "Other (please specify)"
    validations:
      required: true

  - type: input
    id: device_model_other
    attributes:
      label: Other Device Model
      description: If you selected "Other", specify the model
      placeholder: "e.g., ecoMax 920i2"
    validations:
      required: false

  - type: dropdown
    id: feature_type
    attributes:
      label: Feature Type
      description: What kind of feature is this?
      options:
        - "New entity (sensor/binary_sensor/switch/select/number)"
        - "New service/action"
        - "UI / usability"
        - "Performance / reliability"
        - "Documentation"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: feature_description
    attributes:
      label: What do you want to add/change?
      description: Describe the feature clearly so the expected result is clear.
      placeholder: "Example: Add ambient room temperature from panel as a sensor"
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Why is it useful?
      description: Describe your use case / why you need it.
      placeholder: "Example: I want to use the ambient temp in automations and dashboards"
    validations:
      required: true

  - type: input
    id: api_parameter
    attributes:
      label: API Parameter Name (optional)
      description: If you know the exact ecoNET API key, put it here.
      placeholder: "e.g., tempCO, roomTemp, mixerTemp1"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ### Diagnostics (optional but very helpful)
        Attach **ecoNET300 diagnostics** from Home Assistant (automatically redacted):

        **Settings → Devices & Services → ecoNET300 → ⋮ → Download diagnostics**

        Docs: https://www.home-assistant.io/integrations/diagnostics/

  - type: textarea
    id: additional_info
    attributes:
      label: Anything else? (optional)
      description: Screenshots, logs, links, or other context.
    validations:
      required: false
